---
logging:
  level: INFO
  loggers:
    org.speer: DEBUG

secretKey : WIhFv/WcCq//zsbaQ+bs8/a2teWJ0JjPiKiDrzqIoGZH/2HTGpzKTTzal+dYRSlJYNMRCipqC8L89x9knY64Aw==

dataSourceFactory:
  driverClass: com.mysql.cj.jdbc.Driver
  user: root
  password: DEep@2000
  url: jdbc:mysql://127.0.0.1:3306/SpeerDatabase
  properties:
    charSet: UTF-8  # Optional: Set the character set if needed
    hibernate.dialect: org.hibernate.dialect.MySQLDialect
    hibernate.hbm2ddl.auto: update

permitsPerSecond : 1.0